#!/usr/bin/env php
<?php
/*
 * This file is part of guzzle-cli
 *
 * (c) NetworkRanger <17346503142@163.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

use GuzzleCli\Application;

define('ROOT_PATH', __DIR__);
require ROOT_PATH . '/vendor/autoload.php';

// run the command application
$application = new Application();
$application->run();