#!/usr/bin/env php
<?php
/*
 * This file is part of guzzle-cli
 *
 * (c) NetworkRanger <17346503142@163.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

use GuzzleCli\Cli;
use Symfony\Component\Console\Input\ArgvInput;

define('ROOT_PATH', __DIR__);
define('EXEC_PATH', getcwd());
require ROOT_PATH . '/vendor/autoload.php';

$argvInput = new ArgvInput();

if ($argvInput->hasParameterOption('-r')) {
    $file_full_path = $argvInput->getParameterOption('-r');
    try {
        $config = [];
        if ($argvInput->hasParameterOption('--proxy')) {
            $config['proxy'] = $argvInput->getParameterOption('--proxy');
        }

        (new Cli($file_full_path))->send($config);
    } catch (Throwable $throwable) {
        echo $throwable->getTraceAsString();
    }
} else {
    GuzzleCli\print_guzzle_cli_usage();
}